server:
  port: 8081

security:
  jwt:
    secret: "abc"
    expire-length: 15 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
spring:
  jackson:
    default-property-inclusion: NON_NULL
