server:
  port: 8081

security:
  jwt:
    secret: "abc"
    expire-length: 15 #minute

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    _org.springframework.web.servlet.HandlerMapping.Mappings: debug

spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/fnb
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
